FROM restreamio/gstreamer:latest-dev-dependencies

ARG GSTREAMER_REPOSITORY=https://gitlab.freedesktop.org/gstreamer/gstreamer.git
ARG GSTREAMER_CHECKOUT=master

ARG LIBWPE_VERSION=1.8.0
ARG WPEBACKEND_FDO_VERSION=1.8.0
ARG WPEWEBKIT_VERSION=2.30.2

ARG LIBNICE_REPOSITORY=https://gitlab.freedesktop.org/libnice/libnice.git
ARG LIBNICE_CHECKOUT=master

ARG GST_PLUGINS_BASE_REPOSITORY=https://gitlab.freedesktop.org/gstreamer/gst-plugins-base.git
ARG GST_PLUGINS_BASE_CHECKOUT=master

ARG GST_PLUGINS_BAD_REPOSITORY=https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad.git
ARG GST_PLUGINS_BAD_CHECKOUT=master

ARG GST_PLUGINS_GOOD_REPOSITORY=https://gitlab.freedesktop.org/gstreamer/gst-plugins-good.git
ARG GST_PLUGINS_GOOD_CHECKOUT=master

ARG GST_PLUGINS_UGLY_REPOSITORY=https://gitlab.freedesktop.org/gstreamer/gst-plugins-ugly.git
ARG GST_PLUGINS_UGLY_CHECKOUT=master

ARG GST_LIBAV_REPOSITORY=https://gitlab.freedesktop.org/gstreamer/gst-libav.git
ARG GST_LIBAV_CHECKOUT=master

COPY docker/build-gstreamer/download /

RUN ["/download"]

COPY docker/build-gstreamer/compile /
